using System.Text.Json;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Hosting.Server.Features;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using PactNet;
using PactNet.Output.Xunit;
using PactNet.Verifier;
using Xunit;
using Xunit.Abstractions;

namespace ContractTests.Provider;

/// <summary>
/// Pact provider verification tests for the Customer service.
///
/// Verifies that the Customer service honours the API contract defined
/// by the Order service consumer tests. The pact file is generated by
/// <see cref="Consumer.OrderCustomerConsumerTests"/>.
///
/// Uses the Customer service's in-memory seed data (no database required).
/// </summary>
public class CustomerProviderTests : IAsyncLifetime
{
    private readonly ITestOutputHelper _output;
    private WebApplication _app = null!;
    private string _serverUrl = null!;

    public CustomerProviderTests(ITestOutputHelper output)
    {
        _output = output;
    }

    public async Task InitializeAsync()
    {
        var builder = WebApplication.CreateBuilder();

        // Port 0 = OS-assigned random port

        builder.Services.AddControllers()
            .AddApplicationPart(typeof(Customer.API.Controllers.CustomerController).Assembly);

        _app = builder.Build();

        _app.Urls.Add("http://127.0.0.1:0");

        // Provider state endpoint for Pact verification.
        // The Customer service uses static seed data, so most states
        // require no setup — the data is already present.
        _app.MapPost("/provider-states", async (HttpContext ctx) =>
        {
            using var reader = new StreamReader(ctx.Request.Body);
            var body = await reader.ReadToEndAsync();
            var providerState = JsonSerializer.Deserialize<ProviderStateRequest>(
                body, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            _output.WriteLine($"Provider state requested: {providerState?.State}");

            // Seed data already contains customer c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f
            // and does not contain 00000000-0000-0000-0000-000000000000, so all states
            // are naturally satisfied.

            ctx.Response.StatusCode = 200;
        });

        _app.MapControllers();

        await _app.StartAsync();

        var server = _app.Services.GetRequiredService<IServer>();
        var addresses = server.Features.Get<IServerAddressesFeature>();
        _serverUrl = addresses!.Addresses.First();
    }

    public async Task DisposeAsync()
    {
        await _app.DisposeAsync();
    }

    [Fact]
    public void CustomerService_HonoursOrderServicePact()
    {
        var pactDir = Path.GetFullPath(Path.Combine(
            AppContext.BaseDirectory, "..", "..", "..", "..", "..", "pacts"));
        var pactFile = Path.Combine(pactDir, "OrderService-CustomerService.json");

        _output.WriteLine($"Looking for pact file at: {pactFile}");

        if (!File.Exists(pactFile))
        {
            Assert.Fail($"Pact file not found at {pactFile}. Run consumer tests first.");
            return;
        }

        var verifier = new PactVerifier("CustomerService", new PactVerifierConfig
        {
            LogLevel = PactLogLevel.Information,
            Outputters = [new XunitOutput(_output)]
        });

        verifier
            .WithHttpEndpoint(new Uri(_serverUrl))
            .WithFileSource(new FileInfo(pactFile))
            .WithProviderStateUrl(new Uri($"{_serverUrl}/provider-states"))
            .Verify();
    }

    private record ProviderStateRequest(string State, Dictionary<string, object>? Params);
}
