using System.Text.Json;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Hosting.Server.Features;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Notification.API.Services;
using Notification.Domain.Entities;
using Notification.Domain.Interfaces;
using Notification.Infrastructure.Data;
using Notification.Infrastructure.Repositories;
using PactNet;
using PactNet.Output.Xunit;
using PactNet.Verifier;
using Xunit;
using Xunit.Abstractions;

namespace ContractTests.Provider;

/// <summary>
/// Pact provider verification tests for the Notification service.
///
/// Verifies that the Notification service honours the API contract defined
/// by the Order service consumer tests. The pact file is generated by
/// <see cref="Consumer.OrderNotificationConsumerTests"/>.
///
/// Uses an in-memory database and self-hosted Kestrel for isolation.
/// </summary>
public class NotificationProviderTests : IAsyncLifetime
{
    private const string TestDbName = "NotificationPactTestDb";

    private static readonly Guid SeedNotificationId = Guid.Parse("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e");
    private static readonly Guid SeedOrderId = Guid.Parse("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d");
    private static readonly Guid SeedCustomerId = Guid.Parse("c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f");

    private readonly ITestOutputHelper _output;
    private WebApplication _app = null!;
    private string _serverUrl = null!;

    public NotificationProviderTests(ITestOutputHelper output)
    {
        _output = output;
    }

    public async Task InitializeAsync()
    {
        var builder = WebApplication.CreateBuilder();

        builder.Services.AddControllers()
            .AddApplicationPart(typeof(Notification.API.Controllers.NotificationController).Assembly);

        builder.Services.AddDbContext<NotificationDbContext>(options =>
            options.UseInMemoryDatabase(TestDbName));

        builder.Services.AddScoped<INotificationRepository, NotificationRepository>();
        builder.Services.AddScoped<NotificationRenderer>();
        builder.Services.AddScoped<OrderEventConsumer>();

        _app = builder.Build();

        _app.Urls.Add("http://127.0.0.1:0");

        // Provider state endpoint for Pact verification
        _app.MapPost("/provider-states", async (HttpContext ctx) =>
        {
            using var reader = new StreamReader(ctx.Request.Body);
            var body = await reader.ReadToEndAsync();
            var providerState = JsonSerializer.Deserialize<ProviderStateRequest>(
                body, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            _output.WriteLine($"Provider state: {providerState?.State}");

            if (providerState?.State == "a notification with the specified ID exists")
            {
                using var scope = ctx.RequestServices.CreateScope();
                var db = scope.ServiceProvider.GetRequiredService<NotificationDbContext>();

                var existing = await db.OrderNotifications.FindAsync(SeedNotificationId);
                if (existing is null)
                {
                    db.OrderNotifications.Add(CreateSeedNotification());
                    await db.SaveChangesAsync();
                    _output.WriteLine("Seeded notification into database");
                }
            }

            ctx.Response.StatusCode = 200;
        });

        _app.MapControllers();

        // Pre-seed the notification so it's always available for GET tests
        using (var scope = _app.Services.CreateScope())
        {
            var db = scope.ServiceProvider.GetRequiredService<NotificationDbContext>();
            db.Database.EnsureCreated();
            db.OrderNotifications.Add(CreateSeedNotification());
            await db.SaveChangesAsync();
        }

        await _app.StartAsync();

        var server = _app.Services.GetRequiredService<IServer>();
        var addresses = server.Features.Get<IServerAddressesFeature>();
        _serverUrl = addresses!.Addresses.First();

        _output.WriteLine($"Notification provider started at {_serverUrl}");
    }

    public async Task DisposeAsync()
    {
        await _app.DisposeAsync();
    }

    [Fact]
    public void NotificationService_HonoursOrderServicePact()
    {
        var pactDir = Path.GetFullPath(Path.Combine(
            AppContext.BaseDirectory, "..", "..", "..", "..", "..", "pacts"));
        var pactFile = Path.Combine(pactDir, "OrderService-NotificationService.json");

        _output.WriteLine($"Looking for pact file at: {pactFile}");

        if (!File.Exists(pactFile))
        {
            Assert.Fail($"Pact file not found at {pactFile}. Run consumer tests first.");
            return;
        }

        _output.WriteLine("Starting verification...");

        var verifier = new PactVerifier("NotificationService", new PactVerifierConfig
        {
            LogLevel = PactLogLevel.Information,
            Outputters = [new XunitOutput(_output)]
        });

        verifier
            .WithHttpEndpoint(new Uri(_serverUrl))
            .WithFileSource(new FileInfo(pactFile))
            .WithProviderStateUrl(new Uri($"{_serverUrl}/provider-states"))
            .Verify();
    }

    private static OrderNotification CreateSeedNotification() => new()
    {
        Id = SeedNotificationId,
        OrderId = SeedOrderId,
        CustomerId = SeedCustomerId,
        OrderTotal = 4999m,
        CustomerEmail = "customer@example.com",
        CustomerName = "Valued Customer",
        Type = NotificationType.OrderConfirmation,
        Status = NotificationStatus.Rendered,
        RenderedSubject = "Order Confirmation",
        RenderedBody = "<html><body>Order Confirmed</body></html>",
        CreatedAt = DateTime.Parse("2025-06-01T12:00:00Z").ToUniversalTime()
    };

    private record ProviderStateRequest(string State, Dictionary<string, object>? Params);
}
